BAJAR DATOS DEL REGISTRO DE LA PROPIEDAD DEL PAIS VASCO

In [1]:
import pandas as pd

In [26]:
import pandas as pd

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral23/opendata/2023.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.assign(Fecha='2023-03-30')
df_compraventa_2023_1 = df.iloc[:76] #primeras 70 filas
df_compraventa_2023_1.assign(Tipo='Num_compraventas')

,desglose,Territorio,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,161.024,30.466,130.558,2023-03-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,6.110,1.212,4.898,2023-03-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,32.309,6.788,25.521,2023-03-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.952,658,3.294,2023-03-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3.141,512,2.629,2023-03-30,Num_compraventas
...,...,...,...,...,...,...,...
71,1.1.1.- Etxebizitzen batez besteko prezioa (...,NaN,NaN,NaN,NaN,2023-03-30,Num_compraventas
72,1.1.1.- Precio medio de vivienda (/m2). 01 tr...,NaN,NaN,NaN,NaN,2023-03-30,Num_compraventas
73,NaN,NaN,NaN,NaN,NaN,2023-03-30,Num_compraventas
74,BANATZEA ...,EREMUA ...,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,2023-03-30,Num_compraventas
75,Nazionala/Nacional,ESPAÑA,"1.920,75","2.124,27","1.873,24",2023-03-30,Num_compraventas

In [27]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral23/opendata/2023.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.assign(Fecha='2023-06-30')
df_compraventa_2023_2 = df.iloc[:76] #primeras 70 filas
df_compraventa_2023_2.assign(Tipo='Num_compraventas')

,desglose,Territorio,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,151983,28739,123244,2023-06-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5038,663,4375,2023-06-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,30698,6269,24429,2023-06-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3966,819,3147,2023-06-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3145,656,2489,2023-06-30,Num_compraventas
...,...,...,...,...,...,...,...
71,1.1.1.- Etxebizitzen batez besteko prezioa (...,NaN,NaN,NaN,NaN,2023-06-30,Num_compraventas
72,1.1.1.- Precio medio de vivienda (/m2). 02 tr...,NaN,NaN,NaN,NaN,2023-06-30,Num_compraventas
73,NaN,NaN,NaN,NaN,NaN,2023-06-30,Num_compraventas
74,BANATZEA ...,EREMUA ...,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,2023-06-30,Num_compraventas
75,Nazionala/Nacional,ESPAÑA,"1979,48","2212,37","1924,6",2023-06-30,Num_compraventas

In [28]:
df_compraventa_tot = pd.concat([df_compraventa_2023_1 , df_compraventa_2023_2 ])
print(df_compraventa_tot)

                                             desglose  \
0                                  Nazionala/Nacional
1                                  Euskadi/País Vasco
2                             Erakunde Autonomoa/CCAA
3                             Erakunde Autonomoa/CCAA
4                             Erakunde Autonomoa/CCAA
..                                                ...
71  1.1.1.-  Etxebizitzen batez besteko prezioa (...
72  1.1.1.- Precio medio de vivienda (/m2). 02 tr...
73                                                NaN
74  BANATZEA                                      ...
75                                 Nazionala/Nacional

                                           Territorio  OROKORRA GENERAL  \
0                                              ESPAÑA        161.024
1                                  EUSKADI/PAIS VASCO          6.110
2                                 ANDALUZIA/ANDALUCIA         32.309
3                                       ARAGOI/ARAGON          3.952
4                                   ASTURIAS/ASTURIAS          3.141
..                                                ...               ...
71                                                NaN               NaN
72                                                NaN               NaN
73                                                NaN               NaN
74  EREMUA                                        ...  OROKORRA GENERAL
75                                             ESPAÑA           1979,48

        BERRIA NUEVA  ERABILIA USADA       Fecha
0            30.466         130.558   2023-03-30
1             1.212           4.898   2023-03-30
2             6.788          25.521   2023-03-30
3               658           3.294   2023-03-30
4               512           2.629   2023-03-30
..               ...             ...         ...
71               NaN             NaN  2023-06-30
72               NaN             NaN  2023-06-30
73               NaN             NaN  2023-06-30
74  BERRIA     NUEVA  ERABILIA USADA  2023-06-30
75           2212,37          1924,6  2023-06-30

[152 rows x 6 columns]

In [29]:
df_compraventa_tot

,desglose,Territorio,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,Fecha
0,Nazionala/Nacional,ESPAÑA,161.024,30.466,130.558,2023-03-30
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,6.110,1.212,4.898,2023-03-30
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,32.309,6.788,25.521,2023-03-30
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.952,658,3.294,2023-03-30
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3.141,512,2.629,2023-03-30
...,...,...,...,...,...,...
71,1.1.1.- Etxebizitzen batez besteko prezioa (...,NaN,NaN,NaN,NaN,2023-06-30
72,1.1.1.- Precio medio de vivienda (/m2). 02 tr...,NaN,NaN,NaN,NaN,2023-06-30
73,NaN,NaN,NaN,NaN,NaN,2023-06-30
74,BANATZEA ...,EREMUA ...,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,2023-06-30
75,Nazionala/Nacional,ESPAÑA,"1979,48","2212,37","1924,6",2023-06-30

In [30]:
df_compraventa_tot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 0 to 75
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   desglose          146 non-null    object
 1   Territorio        142 non-null    object
 2   OROKORRA GENERAL  142 non-null    object
 3   BERRIA NUEVA      142 non-null    object
 4   ERABILIA USADA    142 non-null    object
 5   Fecha             152 non-null    object
dtypes: object(6)
memory usage: 8.3+ KB

In [31]:
df_compraventa_2023_1 = df.iloc[:76] #primeras 70 filas
df_compraventa_2023_1  = df.assign(Tipo='Num_compraventas')

In [32]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral23/opendata/2023.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.assign(Fecha='2023-06-30')
#print(df)
df_compraventa_2023_2 = df.iloc[:76] #primeras 70 filas
df_compraventa_2023_2  = df.assign(Tipo='Num_compraventas')
df_compraventa_tot = pd.concat([df_compraventa_2023_1 , df_compraventa_2023_2 ])
print(df_compraventa_tot)

                    desglose           Territorio OROKORRA GENERAL  \
0         Nazionala/Nacional               ESPAÑA           151983
1         Euskadi/País Vasco   EUSKADI/PAIS VASCO             5038
2    Erakunde Autonomoa/CCAA  ANDALUZIA/ANDALUCIA            30698
3    Erakunde Autonomoa/CCAA        ARAGOI/ARAGON             3966
4    Erakunde Autonomoa/CCAA    ASTURIAS/ASTURIAS             3145
..                       ...                  ...              ...
814                      NaN                  NaN             2,71
815                      NaN                  NaN             2,62
816                      NaN                  NaN              NaN
817                      NaN                  NaN              NaN
818                      NaN                  NaN              NaN

    BERRIA NUEVA ERABILIA USADA       Fecha              Tipo  \
0          28739         123244  2023-06-30  Num_compraventas
1            663           4375  2023-06-30  Num_compraventas
2           6269          24429  2023-06-30  Num_compraventas
3            819           3147  2023-06-30  Num_compraventas
4            656           2489  2023-06-30  Num_compraventas
..           ...            ...         ...               ...
814          NaN            NaN  2023-06-30  Num_compraventas
815          NaN            NaN  2023-06-30  Num_compraventas
816          NaN            NaN  2023-06-30  Num_compraventas
817          NaN            NaN  2023-06-30  Num_compraventas
818          NaN            NaN  2023-06-30  Num_compraventas

    BANATZEA                                        DESGLOSE  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
814                                     Lurraldea/TTHH
815                                     Lurraldea/TTHH
816                                                NaN
817  Iturria: Erregistratzaileetako eta Euskadiaren...
818  Fuente:  Colegio de Registradores y Registros ...

    EREMUA                                                    ÁMBITO
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
814                                           GIPUZKOA
815                                            BIZKAIA
816                                                NaN
817                                                NaN
818                                                NaN

[1638 rows x 9 columns]

VAMOS A EMPREZAR DESDE EL PRINCIPIO CON LOS LISTADOS DE COMPRAVENTAS

In [33]:
import pandas as pd

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral23/opendata/2023.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2023-06-30')
df_compraventa_2023_2 = df.iloc[:70] #primeras 70 filas
df_compraventa_2023_2.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,151983,28739,123244,2023-06-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5038,663,4375,2023-06-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,30698,6269,24429,2023-06-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3966,819,3147,2023-06-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3145,656,2489,2023-06-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,73,1,72,2023-06-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,182,20,162,2023-06-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,69,n.d.,n.d.,2023-06-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,113,5,108,2023-06-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2023-06-30,Num_compraventas

In [34]:
import pandas as pd

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral23/opendata/2023.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2023-03-30')
df_compraventa_2023_1 = df.iloc[:70] #primeras 70 filas
df_compraventa_2023_1.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,161.024,30.466,130.558,2023-03-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,6.110,1.212,4.898,2023-03-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,32.309,6.788,25.521,2023-03-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.952,658,3.294,2023-03-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3.141,512,2.629,2023-03-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,65,2,63,2023-03-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,154,18,136,2023-03-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,112,4,108,2023-03-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,165,41,124,2023-03-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2023-03-30,Num_compraventas

In [35]:
frames = [df_compraventa_2023_2, df_compraventa_2023_1]  
df_compraventa_2023 = pd.concat(frames, ignore_index=True)
df_compraventa_2023.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,151983,28739,123244,2023-06-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5038,663,4375,2023-06-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,30698,6269,24429,2023-06-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3966,819,3147,2023-06-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3145,656,2489,2023-06-30,Num_compraventas
...,...,...,...,...,...,...,...
135,Udalerriak >40.000/Municipios >40.000,Basauri,65,2,63,2023-03-30,Num_compraventas
136,Udalerriak >40.000/Municipios >40.000,Getxo,154,18,136,2023-03-30,Num_compraventas
137,Udalerriak >40.000/Municipios >40.000,Portugalete,112,4,108,2023-03-30,Num_compraventas
138,Udalerriak >40.000/Municipios >40.000,Santurtzi,165,41,124,2023-03-30,Num_compraventas
139,NaN,NaN,NaN,NaN,NaN,2023-03-30,Num_compraventas

In [36]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral22/opendata/2022.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2022-12-30')
df_compraventa_2022_4 = df.iloc[:70] #primeras 70 filas
df_compraventa_2022_4.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,150141,25862,124279,2022-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5125,970,4155,2022-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,31472,5806,25666,2022-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3551,687,2864,2022-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2726,467,2259,2022-12-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,72,11,61,2022-12-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,173,33,140,2022-12-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,90,16,74,2022-12-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,147,19,128,2022-12-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2022-12-30,Num_compraventas

In [37]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral22/opendata/2022.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2022-09-30')
df_compraventa_2022_3 = df.iloc[:70] #primeras 70 filas
df_compraventa_2022_3.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,167892,28595,139297,2022-09-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5967,762,5205,2022-09-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,34608,6575,28033,2022-09-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,4572,850,3722,2022-09-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2867,553,2314,2022-09-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,81,10,71,2022-09-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,281,39,242,2022-09-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,92,n.d.,n.d.,2022-09-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,129,2,127,2022-09-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2022-09-30,Num_compraventas

In [38]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral22/opendata/ER_2022_2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2022-06-30')
df_compraventa_2022_2 = df.iloc[:70] #primeras 70 filas
df_compraventa_2022_2.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,163.909,27.879,136.030,2022-06-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,6.160,772,5.388,2022-06-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,33.186,6.459,26.727,2022-06-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,4.410,711,3.699,2022-06-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.950,480,2.470,2022-06-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,111,7,104,2022-06-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,160,15,145,2022-06-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,120,1,119,2022-06-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,182,1,181,2022-06-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2022-06-30,Num_compraventas

In [39]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral22/opendata/ER_2022_1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2022-03-30')
df_compraventa_2022_1 = df.iloc[:70] #primeras 70 filas
df_compraventa_2022_1.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,164299,32316,131983,2022-03-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,6371,1129,5242,2022-03-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,34215,7490,26725,2022-03-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,4136,793,3343,2022-03-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2851,547,2304,2022-03-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,140,48,92,2022-03-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,184,17,167,2022-03-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,65,2,63,2022-03-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,91,1,90,2022-03-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2022-03-30,Num_compraventas

In [40]:
frames = [df_compraventa_2022_4, df_compraventa_2022_3, df_compraventa_2022_2, df_compraventa_2022_1]  
df_compraventa_2022 = pd.concat(frames, ignore_index=True)
df_compraventa_2022.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,150141,25862,124279,2022-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5125,970,4155,2022-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,31472,5806,25666,2022-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3551,687,2864,2022-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2726,467,2259,2022-12-30,Num_compraventas
...,...,...,...,...,...,...,...
275,Udalerriak >40.000/Municipios >40.000,Basauri,140,48,92,2022-03-30,Num_compraventas
276,Udalerriak >40.000/Municipios >40.000,Getxo,184,17,167,2022-03-30,Num_compraventas
277,Udalerriak >40.000/Municipios >40.000,Portugalete,65,2,63,2022-03-30,Num_compraventas
278,Udalerriak >40.000/Municipios >40.000,Santurtzi,91,1,90,2022-03-30,Num_compraventas
279,NaN,NaN,NaN,NaN,NaN,2022-03-30,Num_compraventas

In [41]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral21/opendata/2021.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2021-12-30')
df_compraventa_2021_4 = df.iloc[:70] #primeras 70 filas
df_compraventa_2021_4.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,143.982,28.555,115.427,2021-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,4.803,675,4.128,2021-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,31.325,7.453,23.872,2021-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.508,641,2.867,2021-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.388,473,1.915,2021-12-30,Num_compraventas
...,...,...,...,...,...,...,...
65,Udalerriak >40.000/Municipios >40.000,Basauri,108,5,103,2021-12-30,Num_compraventas
66,Udalerriak >40.000/Municipios >40.000,Getxo,152,11,141,2021-12-30,Num_compraventas
67,Udalerriak >40.000/Municipios >40.000,Portugalete,57,4,53,2021-12-30,Num_compraventas
68,Udalerriak >40.000/Municipios >40.000,Santurtzi,84,n.d.,n.d.,2021-12-30,Num_compraventas
69,NaN,NaN,NaN,NaN,NaN,2021-12-30,Num_compraventas

In [42]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral21/opendata/2021.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2021-09-30')
df_compraventa_2021_3 = df.iloc[:60] #primeras x filas
df_compraventa_2021_3.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,154.155,29.433,124.722,2021-09-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5.557,756,4.801,2021-09-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,32.433,7.168,25.265,2021-09-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.818,706,3.112,2021-09-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.442,465,1.977,2021-09-30,Num_compraventas
5,Erakunde Autonomoa/CCAA,BALEAR UHARTEAK/BALEARES,4.519,571,3.948,2021-09-30,Num_compraventas
6,Erakunde Autonomoa/CCAA,KANARIAR UHARTEAK/CANARIAS,6.529,1.462,5.067,2021-09-30,Num_compraventas
7,Erakunde Autonomoa/CCAA,KANTABRIA/CANTABRIA,2.021,299,1.722,2021-09-30,Num_compraventas
8,Erakunde Autonomoa/CCAA,GAZTELA ETA LEON/CASTILLA Y LEON,6.879,1.505,5.374,2021-09-30,Num_compraventas
9,Erakunde Autonomoa/CCAA,GAZTELA-MANTXA/CASTILLA-LA MANCHA,6.343,1.226,5.117,2021-09-30,Num_compraventas
10,Erakunde Autonomoa/CCAA,KATALUNIA/CATALUÑA,24.040,3.733,20.307,2021-09-30,Num_compraventas
11,Erakunde Autonomoa/CCAA,EXTREMADURA/EXTREMADURA,2.274,224,2.050,2021-09-30,Num_compraventas
12,Erakunde Autonomoa/CCAA,GALIZIA/GALICIA,5.216,1.266,3.950,2021-09-30,Num_compraventas
13,Erakunde Autonomoa/CCAA,MADRIL/MADRID,21.685,5.001,16.684,2021-09-30,Num_compraventas
14,Erakunde Autonomoa/CCAA,MURTZIA/MURCIA,5.189,925,4.264,2021-09-30,Num_compraventas
15,Erakunde Autonomoa/CCAA,NAFARROA/NAVARRA,1.817,597,1.220,2021-09-30,Num_compraventas
16,Erakunde Autonomoa/CCAA,ERRIOXA/LA RIOJA,1.216,308,908,2021-09-30,Num_compraventas
17,Erakunde Autonomoa/CCAA,VALENTZIA KOMUNITATEA/VALENCIA,22.177,3.221,18.956,2021-09-30,Num_compraventas
18,Hiriburak/Capitales de TTHH,Vitoria-Gasteiz,560,48,512,2021-09-30,Num_compraventas
19,Hiriburak/Capitales de TTHH,Donostia-San Sebastián,600,115,482,2021-09-30,Num_compraventas
20,Hiriburak/Capitales de TTHH,Bilbao,965,91,874,2021-09-30,Num_compraventas
21,Lurralderen gainerakoa/Resto de TTHH,ARABA/ÁLAVA,205,27,178,2021-09-30,Num_compraventas
22,Lurralderen gainerakoa/Resto de TTHH,GIPUZKOA,1.258,107,1.151,2021-09-30,Num_compraventas
23,Lurralderen gainerakoa/Resto de TTHH,BIZKAIA,1.855,357,1.498,2021-09-30,Num_compraventas
24,Eskualde Egitura/Áreas funcionales,Álava Central,672,58,614,2021-09-30,Num_compraventas
25,Eskualde Egitura/Áreas funcionales,Balmaseda-Zalla,44,6,38,2021-09-30,Num_compraventas
26,Eskualde Egitura/Áreas funcionales,Beasain-Zumárraga,185,10,175,2021-09-30,Num_compraventas
27,Eskualde Egitura/Áreas funcionales,Bilbao Metropolitano,2.393,336,2.057,2021-09-30,Num_compraventas
28,Eskualde Egitura/Áreas funcionales,Donostia-San Sebastián,1.113,153,957,2021-09-30,Num_compraventas
29,Eskualde Egitura/Áreas funcionales,Durango,171,49,122,2021-09-30,Num_compraventas
30,Eskualde Egitura/Áreas funcionales,Eibar,150,41,109,2021-09-30,Num_compraventas
31,Eskualde Egitura/Áreas funcionales,Gernika-Markina,117,31,86,2021-09-30,Num_compraventas
32,Eskualde Egitura/Áreas funcionales,Igorre,22,3,19,2021-09-30,Num_compraventas
33,Eskualde Egitura/Áreas funcionales,Laguardia,31,12,19,2021-09-30,Num_compraventas
34,Eskualde Egitura/Áreas funcionales,Laudio / Llodio,73,9,64,2021-09-30,Num_compraventas
35,Eskualde Egitura/Áreas funcionales,Arrasate-Bergara,105,25,80,2021-09-30,Num_compraventas
36,Eskualde Egitura/Áreas funcionales,Mungia,44,10,34,2021-09-30,Num_compraventas
37,Eskualde Egitura/Áreas funcionales,Tolosa,139,n.d.,n.d.,2021-09-30,Num_compraventas
38,Eskualde Egitura/Áreas funcionales,Zarautz-Azpeitia,184,2,182,2021-09-30,Num_compraventas
39,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 01,34,1,33,2021-09-30,Num_compraventas
40,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 02,61,n.d.,n.d.,2021-09-30,Num_compraventas
41,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 03,167,16,151,2021-09-30,Num_compraventas
42,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 04,121,9,112,2021-09-30,Num_compraventas
43,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 05,67,9,58,2021-09-30,Num_compraventas
44,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 06,99,9,90,2021-09-30,Num_compraventas
45,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 01,20,n.d.,n.d.,2021-09-30,Num_compraventas
46,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 02,80,21,59,2021-09-30,Num_compraventas
47,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 03,66,1,65,2021-09-30,Num_compraventas
48,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 04,105,12,93,2021-09-30,Num_compraventas
49,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 05,92,5,87,2021-09-30,Num_compraventas
50,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 06,231,76,152,2021-09-30,Num_compraventas
51,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 01,123,2,121,2021-09-30,Num_compraventas
52,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 02,130,34,96,2021-09-30,Num_compraventas
53,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 03,34,n.d.,n.d.,2021-09-30,Num_compraventas
54,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 04,77,2,75,2021-09-30,Num_compraventas
55,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,150,4,146,2021-09-30,Num_compraventas
56,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,165,19,146,2021-09-30,Num_compraventas
57,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,170,2,168,2021-09-30,Num_compraventas
58,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,76,6,70,2021-09-30,Num_compraventas
59,NaN,NaN,NaN,NaN,NaN,2021-09-30,Num_compraventas

In [43]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral21/opendata/Estadistica-Registradores-2021.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2021-06-30')
df_compraventa_2021_2 = df.iloc[:60] #primeras x filas
df_compraventa_2021_2.assign(Tipo='Num_compraventas')

,Desglose,Territorio,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,"137.204,00","26.384,00","110.820,00",2021-06-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,"5.790,00","894,00","4.896,00",2021-06-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,"27.905,00","5.583,00","22.322,00",2021-06-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,"4.026,00","743,00","3.283,00",2021-06-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,"2.335,00","479,00","1.856,00",2021-06-30,Num_compraventas
5,Erakunde Autonomoa/CCAA,BALEAR UHARTEAK/BALEARES,"3.132,00","554,00","2.578,00",2021-06-30,Num_compraventas
6,Erakunde Autonomoa/CCAA,KANARIAR UHARTEAK/CANARIAS,"5.082,00","1.070,00","4.012,00",2021-06-30,Num_compraventas
7,Erakunde Autonomoa/CCAA,KANTABRIA/CANTABRIA,"1.732,00","253,00","1.479,00",2021-06-30,Num_compraventas
8,Erakunde Autonomoa/CCAA,GAZTELA ETA LEON/CASTILLA Y LEON,"5.923,00","1.133,00","4.790,00",2021-06-30,Num_compraventas
9,Erakunde Autonomoa/CCAA,GAZTELA-MANTXA/CASTILLA-LA MANCHA,"5.525,00","1.019,00","4.506,00",2021-06-30,Num_compraventas
10,Erakunde Autonomoa/CCAA,KATALUNIA/CATALUÑA,"22.062,00","3.469,00","18.593,00",2021-06-30,Num_compraventas
11,Erakunde Autonomoa/CCAA,EXTREMADURA/EXTREMADURA,"2.382,00","247,00","2.135,00",2021-06-30,Num_compraventas
12,Erakunde Autonomoa/CCAA,GALIZIA/GALICIA,"4.540,00","1.100,00","3.440,00",2021-06-30,Num_compraventas
13,Erakunde Autonomoa/CCAA,MADRIL/MADRID,"20.631,00","5.671,00","14.960,00",2021-06-30,Num_compraventas
14,Erakunde Autonomoa/CCAA,MURTZIA/MURCIA,"4.834,00","905,00","3.929,00",2021-06-30,Num_compraventas
15,Erakunde Autonomoa/CCAA,NAFARROA/NAVARRA,"1.525,00","371,00","1.154,00",2021-06-30,Num_compraventas
16,Erakunde Autonomoa/CCAA,ERRIOXA/LA RIOJA,"1.034,00","159,00","875,00",2021-06-30,Num_compraventas
17,Erakunde Autonomoa/CCAA,VALENTZIA KOMUNITATEA/VALENCIA,"18.746,00","2.734,00","16.012,00",2021-06-30,Num_compraventas
18,Hiriburak/Capitales de TTHH,Vitoria-Gasteiz,"609,00","65,00","544,00",2021-06-30,Num_compraventas
19,Hiriburak/Capitales de TTHH,Donostia-San Sebastián,"559,00","93,00","466,00",2021-06-30,Num_compraventas
20,Hiriburak/Capitales de TTHH,Bilbao,"982,00","51,00","931,00",2021-06-30,Num_compraventas
21,Lurralderen gainerakoa/Resto de TTHH,ARABA/ÁLAVA,"239,00","55,00","184,00",2021-06-30,Num_compraventas
22,Lurralderen gainerakoa/Resto de TTHH,GIPUZKOA,"1.354,00","218,00","1.136,00",2021-06-30,Num_compraventas
23,Lurralderen gainerakoa/Resto de TTHH,BIZKAIA,"1.884,00","402,00","1.482,00",2021-06-30,Num_compraventas
24,Eskualde Egitura/Áreas funcionales,Álava Central,"721,00","74,00","647,00",2021-06-30,Num_compraventas
25,Eskualde Egitura/Áreas funcionales,Balmaseda-Zalla,"55,00",n.d.,n.d.,2021-06-30,Num_compraventas
26,Eskualde Egitura/Áreas funcionales,Beasain-Zumárraga,"200,00","17,00","183,00",2021-06-30,Num_compraventas
27,Eskualde Egitura/Áreas funcionales,Bilbao Metropolitano,"2.394,00","334,00","2.060,00",2021-06-30,Num_compraventas
28,Eskualde Egitura/Áreas funcionales,Donostia-San Sebastián,"1.121,00","199,00","922,00",2021-06-30,Num_compraventas
29,Eskualde Egitura/Áreas funcionales,Durango,"172,00","58,00","114,00",2021-06-30,Num_compraventas
30,Eskualde Egitura/Áreas funcionales,Eibar,"162,00","48,00","114,00",2021-06-30,Num_compraventas
31,Eskualde Egitura/Áreas funcionales,Gernika-Markina,"132,00","36,00","96,00",2021-06-30,Num_compraventas
32,Eskualde Egitura/Áreas funcionales,Igorre,"24,00","2,00","22,00",2021-06-30,Num_compraventas
33,Eskualde Egitura/Áreas funcionales,Laguardia,"25,00","8,00","17,00",2021-06-30,Num_compraventas
34,Eskualde Egitura/Áreas funcionales,Laudio / Llodio,"112,00","40,00","72,00",2021-06-30,Num_compraventas
35,Eskualde Egitura/Áreas funcionales,Arrasate-Bergara,"102,00","37,00","65,00",2021-06-30,Num_compraventas
36,Eskualde Egitura/Áreas funcionales,Mungia,"46,00","6,00","40,00",2021-06-30,Num_compraventas
37,Eskualde Egitura/Áreas funcionales,Tolosa,"143,00","14,00","129,00",2021-06-30,Num_compraventas
38,Eskualde Egitura/Áreas funcionales,Zarautz-Azpeitia,"218,00","11,00","207,00",2021-06-30,Num_compraventas
39,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 01,"33,00","4,00","29,00",2021-06-30,Num_compraventas
40,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 02,"93,00","1,00","92,00",2021-06-30,Num_compraventas
41,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 03,"171,00","28,00","143,00",2021-06-30,Num_compraventas
42,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 04,"140,00","14,00","126,00",2021-06-30,Num_compraventas
43,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 05,"65,00","9,00","56,00",2021-06-30,Num_compraventas
44,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 06,"100,00","9,00","91,00",2021-06-30,Num_compraventas
45,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 01,"25,00",n.d.,n.d.,2021-06-30,Num_compraventas
46,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 02,"90,00","30,00","60,00",2021-06-30,Num_compraventas
47,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 03,"64,00","3,00","61,00",2021-06-30,Num_compraventas
48,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 04,"94,00","5,00","89,00",2021-06-30,Num_compraventas
49,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 05,"95,00","5,00","90,00",2021-06-30,Num_compraventas
50,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 06,"190,00","50,00","140,00",2021-06-30,Num_compraventas
51,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 01,"119,00","2,00","117,00",2021-06-30,Num_compraventas
52,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 02,"92,00",n.d.,n.d.,2021-06-30,Num_compraventas
53,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 03,"51,00",n.d.,n.d.,2021-06-30,Num_compraventas
54,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 04,"111,00","1,00","110,00",2021-06-30,Num_compraventas
55,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,"190,00","3,00","187,00",2021-06-30,Num_compraventas
56,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,"169,00","33,00","136,00",2021-06-30,Num_compraventas
57,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,"157,00","6,00","151,00",2021-06-30,Num_compraventas
58,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,"83,00","6,00","77,00",2021-06-30,Num_compraventas
59,NaN,NaN,NaN,NaN,NaN,2021-06-30,Num_compraventas

In [44]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral21/opendata/Estadistica-Registradores-2021.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2021-03-30')
df_compraventa_2021_1 = df.iloc[:60] #primeras x filas
df_compraventa_2021_1.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,129.228,28.192,101.036,2021-03-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5.413,1.067,4.346,2021-03-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,25.673,5.697,19.976,2021-03-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.514,707,2.807,2021-03-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.390,534,1.856,2021-03-30,Num_compraventas
5,Erakunde Autonomoa/CCAA,BALEAR UHARTEAK/BALEARES,2.889,649,2.240,2021-03-30,Num_compraventas
6,Erakunde Autonomoa/CCAA,KANARIAR UHARTEAK/CANARIAS,4.613,1.082,3.531,2021-03-30,Num_compraventas
7,Erakunde Autonomoa/CCAA,KANTABRIA/CANTABRIA,1.809,307,1.502,2021-03-30,Num_compraventas
8,Erakunde Autonomoa/CCAA,GAZTELA ETA LEON/CASTILLA Y LEON,5.636,1.147,4.489,2021-03-30,Num_compraventas
9,Erakunde Autonomoa/CCAA,GAZTELA-MANTXA/CASTILLA-LA MANCHA,5.417,1.189,4.228,2021-03-30,Num_compraventas
10,Erakunde Autonomoa/CCAA,KATALUNIA/CATALUÑA,20.902,3.736,17.166,2021-03-30,Num_compraventas
11,Erakunde Autonomoa/CCAA,EXTREMADURA/EXTREMADURA,2.262,276,1.986,2021-03-30,Num_compraventas
12,Erakunde Autonomoa/CCAA,GALIZIA/GALICIA,4.699,1.244,3.455,2021-03-30,Num_compraventas
13,Erakunde Autonomoa/CCAA,MADRIL/MADRID,19.339,6.132,13.207,2021-03-30,Num_compraventas
14,Erakunde Autonomoa/CCAA,MURTZIA/MURCIA,4.487,781,3.706,2021-03-30,Num_compraventas
15,Erakunde Autonomoa/CCAA,NAFARROA/NAVARRA,1.683,616,1.067,2021-03-30,Num_compraventas
16,Erakunde Autonomoa/CCAA,ERRIOXA/LA RIOJA,1.006,165,841,2021-03-30,Num_compraventas
17,Erakunde Autonomoa/CCAA,VALENTZIA KOMUNITATEA/VALENCIA,17.496,2.863,14.633,2021-03-30,Num_compraventas
18,Hiriburak/Capitales de TTHH,Vitoria-Gasteiz,627,101,526,2021-03-30,Num_compraventas
19,Hiriburak/Capitales de TTHH,Donostia-San Sebastián,416,93,323,2021-03-30,Num_compraventas
20,Hiriburak/Capitales de TTHH,Bilbao,784,58,726,2021-03-30,Num_compraventas
21,Lurralderen gainerakoa/Resto de TTHH,ARABA/ÁLAVA,175,16,159,2021-03-30,Num_compraventas
22,Lurralderen gainerakoa/Resto de TTHH,GIPUZKOA,1.254,226,1.028,2021-03-30,Num_compraventas
23,Lurralderen gainerakoa/Resto de TTHH,BIZKAIA,1.765,513,1.252,2021-03-30,Num_compraventas
24,Eskualde Egitura/Áreas funcionales,Álava Central,723,108,615,2021-03-30,Num_compraventas
25,Eskualde Egitura/Áreas funcionales,Balmaseda-Zalla,36,n.d.,n.d.,2021-03-30,Num_compraventas
26,Eskualde Egitura/Áreas funcionales,Beasain-Zumárraga,210,64,146,2021-03-30,Num_compraventas
27,Eskualde Egitura/Áreas funcionales,Bilbao Metropolitano,2.181,489,1.692,2021-03-30,Num_compraventas
28,Eskualde Egitura/Áreas funcionales,Donostia-San Sebastián,947,188,759,2021-03-30,Num_compraventas
29,Eskualde Egitura/Áreas funcionales,Durango,136,38,98,2021-03-30,Num_compraventas
30,Eskualde Egitura/Áreas funcionales,Eibar,137,35,102,2021-03-30,Num_compraventas
31,Eskualde Egitura/Áreas funcionales,Gernika-Markina,105,33,72,2021-03-30,Num_compraventas
32,Eskualde Egitura/Áreas funcionales,Igorre,21,3,18,2021-03-30,Num_compraventas
33,Eskualde Egitura/Áreas funcionales,Laguardia,13,2,11,2021-03-30,Num_compraventas
34,Eskualde Egitura/Áreas funcionales,Laudio / Llodio,77,7,70,2021-03-30,Num_compraventas
35,Eskualde Egitura/Áreas funcionales,Arrasate-Bergara,88,26,62,2021-03-30,Num_compraventas
36,Eskualde Egitura/Áreas funcionales,Mungia,39,5,34,2021-03-30,Num_compraventas
37,Eskualde Egitura/Áreas funcionales,Tolosa,149,8,141,2021-03-30,Num_compraventas
38,Eskualde Egitura/Áreas funcionales,Zarautz-Azpeitia,159,1,158,2021-03-30,Num_compraventas
39,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 01,24,1,23,2021-03-30,Num_compraventas
40,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 02,97,7,90,2021-03-30,Num_compraventas
41,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 03,140,37,103,2021-03-30,Num_compraventas
42,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 04,116,9,107,2021-03-30,Num_compraventas
43,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 05,60,4,56,2021-03-30,Num_compraventas
44,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 06,162,38,124,2021-03-30,Num_compraventas
45,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 01,17,n.d.,n.d.,2021-03-30,Num_compraventas
46,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 02,110,53,57,2021-03-30,Num_compraventas
47,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 03,51,2,49,2021-03-30,Num_compraventas
48,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 04,60,4,56,2021-03-30,Num_compraventas
49,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 05,48,2,46,2021-03-30,Num_compraventas
50,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 06,128,32,96,2021-03-30,Num_compraventas
51,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 01,84,n.d.,n.d.,2021-03-30,Num_compraventas
52,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 02,93,1,92,2021-03-30,Num_compraventas
53,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 03,62,n.d.,n.d.,2021-03-30,Num_compraventas
54,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 04,81,n.d.,n.d.,2021-03-30,Num_compraventas
55,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,125,6,119,2021-03-30,Num_compraventas
56,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,131,25,106,2021-03-30,Num_compraventas
57,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,141,18,123,2021-03-30,Num_compraventas
58,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,61,8,53,2021-03-30,Num_compraventas
59,NaN,NaN,NaN,NaN,NaN,2021-03-30,Num_compraventas

In [45]:
frames = [df_compraventa_2021_4, df_compraventa_2021_3, df_compraventa_2021_2, df_compraventa_2021_1]  
df_compraventa_2021 = pd.concat(frames, ignore_index=True)
df_compraventa_2021.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,Tipo
0,Nazionala/Nacional,ESPAÑA,143.982,28.555,115.427,2021-12-30,NaN,NaN,NaN,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,4.803,675,4.128,2021-12-30,NaN,NaN,NaN,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,31.325,7.453,23.872,2021-12-30,NaN,NaN,NaN,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.508,641,2.867,2021-12-30,NaN,NaN,NaN,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.388,473,1.915,2021-12-30,NaN,NaN,NaN,Num_compraventas
...,...,...,...,...,...,...,...,...,...,...
245,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,125,6,119,2021-03-30,NaN,NaN,NaN,Num_compraventas
246,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,131,25,106,2021-03-30,NaN,NaN,NaN,Num_compraventas
247,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,141,18,123,2021-03-30,NaN,NaN,NaN,Num_compraventas
248,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,61,8,53,2021-03-30,NaN,NaN,NaN,Num_compraventas
249,NaN,NaN,NaN,NaN,NaN,2021-03-30,NaN,NaN,NaN,Num_compraventas

In [47]:
df_compraventa_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Desglose            246 non-null    object
 1   Territorio          246 non-null    object
 2   Viv. GENERAL        187 non-null    object
 3   Viv. NUEVA          187 non-null    object
 4   Viv. USADA          187 non-null    object
 5   Fecha               250 non-null    object
 6    OROKORRA GENERAL   59 non-null     object
 7    BERRIA NUEVA       59 non-null     object
 8    ERABILIA USADA     59 non-null     object
dtypes: object(9)
memory usage: 17.7+ KB

In [50]:
# observo que en el dataset combinado, aparecen unas columnas vacias que habria que suprimir
df_compraventa_2021.drop(columns=[' OROKORRA GENERAL',' BERRIA NUEVA',' ERABILIA USADA'], inplace=True)
df_compraventa_2021

KeyError: "[' OROKORRA GENERAL', ' BERRIA NUEVA', ' ERABILIA USADA'] not found in axis"

In [ ]:
df_compraventa_2021.drop('OROKORRA GENERAL', axis=1, inplace=True)
df_compraventa_2021

KeyError: "['OROKORRA GENERAL'] not found in axis"

In [ ]:
# observo que en el dataset combinado, aparecen unas columnas vacias que habria que suprimir
# df_compraventa_2021.drop(columns=[7,8,9], axis=1)
# df_compraventa_2021

In [ ]:
import pandas as pd
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral20/opendata/ER-2020.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2020-12-30')
df_compraventa_2020_4 = df.iloc[:60] #primeras 70 filas
df_compraventa_2020_4.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral20/opendata/2020.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2020-09-30')
df_compraventa_2020_3 = df.iloc[:60] #primeras 70 filas
df_compraventa_2020_3.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral20/opendata/2020.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2020-06-30')
df_compraventa_2020_2 = df.iloc[:60] #primeras 70 filas
df_compraventa_2020_2.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral20/opendata/2020.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras cinco columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2020-03-30')
df_compraventa_2020_1 = df.iloc[:60] #primeras 70 filas
df_compraventa_2020_1.assign(Tipo='Num_compraventas')

,Desglose,EREMUA ÁMBITO,Viv. GENERAL,BERRIA NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,"1.757,80","1.957,27","1.709,99",2020-03-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,"2.787,22","3.038,06","2.739,02",2020-03-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,"1.411,85","1.574,75","1.373,40",2020-03-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,"1.406,11","1.831,39","1.273,92",2020-03-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,"1.222,28","1.376,24","1.176,22",2020-03-30,Num_compraventas
5,Erakunde Autonomoa/CCAA,BALEAR UHARTEAK/BALEARES,"2.584,60","2.537,42","2.595,31",2020-03-30,Num_compraventas
6,Erakunde Autonomoa/CCAA,KANARIAR UHARTEAK/CANARIAS,"1.837,41","1.540,31","1.906,74",2020-03-30,Num_compraventas
7,Erakunde Autonomoa/CCAA,KANTABRIA/CANTABRIA,"1.479,60","1.544,23","1.467,63",2020-03-30,Num_compraventas
8,Erakunde Autonomoa/CCAA,GAZTELA ETA LEON/CASTILLA Y LEON,"1.071,05","1.257,90","1.029,26",2020-03-30,Num_compraventas
9,Erakunde Autonomoa/CCAA,GAZTELA-MANTXA/CASTILLA-LA MANCHA,"838,18","1.050,38","779,70",2020-03-30,Num_compraventas
10,Erakunde Autonomoa/CCAA,KATALUNIA/CATALUÑA,"2.221,88","2.534,62","2.157,77",2020-03-30,Num_compraventas
11,Erakunde Autonomoa/CCAA,EXTREMADURA/EXTREMADURA,"787,24","1.237,20","697,95",2020-03-30,Num_compraventas
12,Erakunde Autonomoa/CCAA,GALIZIA/GALICIA,"1.313,82","1.370,69","1.296,30",2020-03-30,Num_compraventas
13,Erakunde Autonomoa/CCAA,MADRIL/MADRID,"2.745,36","2.725,22","2.752,36",2020-03-30,Num_compraventas
14,Erakunde Autonomoa/CCAA,MURTZIA/MURCIA,"981,94","1.133,23","950,45",2020-03-30,Num_compraventas
15,Erakunde Autonomoa/CCAA,NAFARROA/NAVARRA,"1.755,42","2.061,48","1.642,34",2020-03-30,Num_compraventas
16,Erakunde Autonomoa/CCAA,ERRIOXA/LA RIOJA,"1.088,00","1.257,01","1.042,53",2020-03-30,Num_compraventas
17,Erakunde Autonomoa/CCAA,VALENTZIA KOMUNITATEA/VALENCIA,"1.275,07","1.654,27","1.207,48",2020-03-30,Num_compraventas
18,Hiriburak/Capitales de TTHH,Vitoria-Gasteiz,"2.067,87","2.407,77","2.012,40",2020-03-30,Num_compraventas
19,Hiriburak/Capitales de TTHH,Donostia-San Sebastián,"4.725,43","4.429,36","4.834,64",2020-03-30,Num_compraventas
20,Hiriburak/Capitales de TTHH,Bilbao,"2.696,67","3.207,69","2.673,14",2020-03-30,Num_compraventas
21,Lurralderen gainerakoa/Resto de TTHH,ARABA/ÁLAVA,"1.531,77","2.120,95","1.432,60",2020-03-30,Num_compraventas
22,Lurralderen gainerakoa/Resto de TTHH,GIPUZKOA,"2.425,40","2.155,29","2.468,03",2020-03-30,Num_compraventas
23,Lurralderen gainerakoa/Resto de TTHH,BIZKAIA,"2.781,93","3.012,31","2.722,68",2020-03-30,Num_compraventas
24,Eskualde Egitura/Áreas funcionales,Álava Central,"1.989,57","2.333,20","1.934,43",2020-03-30,Num_compraventas
25,Eskualde Egitura/Áreas funcionales,Balmaseda-Zalla,"1.779,91",n.d.,n.d.,2020-03-30,Num_compraventas
26,Eskualde Egitura/Áreas funcionales,Beasain-Zumárraga,"1.948,62","2.455,46","1.806,71",2020-03-30,Num_compraventas
27,Eskualde Egitura/Áreas funcionales,Bilbao Metropolitano,"2.807,76","3.312,46","2.735,92",2020-03-30,Num_compraventas
28,Eskualde Egitura/Áreas funcionales,Donostia-San Sebastián,"3.623,85","3.710,77","3.602,61",2020-03-30,Num_compraventas
29,Eskualde Egitura/Áreas funcionales,Durango,"2.629,69","2.471,79","2.774,11",2020-03-30,Num_compraventas
30,Eskualde Egitura/Áreas funcionales,Eibar,"2.038,81","1.652,58","2.182,42",2020-03-30,Num_compraventas
31,Eskualde Egitura/Áreas funcionales,Gernika-Markina,"2.207,29",n.d.,n.d.,2020-03-30,Num_compraventas
32,Eskualde Egitura/Áreas funcionales,Igorre,"1.950,93",n.d.,n.d.,2020-03-30,Num_compraventas
33,Eskualde Egitura/Áreas funcionales,Laguardia,"1.526,45",n.d.,n.d.,2020-03-30,Num_compraventas
34,Eskualde Egitura/Áreas funcionales,Laudio / Llodio,"1.792,92",n.d.,n.d.,2020-03-30,Num_compraventas
35,Eskualde Egitura/Áreas funcionales,Arrasate-Bergara,"1.828,96","2.171,88","1.740,06",2020-03-30,Num_compraventas
36,Eskualde Egitura/Áreas funcionales,Mungia,"2.046,54",n.d.,n.d.,2020-03-30,Num_compraventas
37,Eskualde Egitura/Áreas funcionales,Tolosa,"1.861,35",n.d.,n.d.,2020-03-30,Num_compraventas
38,Eskualde Egitura/Áreas funcionales,Zarautz-Azpeitia,"3.092,94",n.d.,n.d.,2020-03-30,Num_compraventas
39,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 01,"1.530,69",n.d.,n.d.,2020-03-30,Num_compraventas
40,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 02,"2.479,83",n.d.,n.d.,2020-03-30,Num_compraventas
41,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 03,"2.304,56","2.587,64","2.185,36",2020-03-30,Num_compraventas
42,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 04,"1.796,24",n.d.,n.d.,2020-03-30,Num_compraventas
43,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 05,"2.041,41",n.d.,n.d.,2020-03-30,Num_compraventas
44,Hiriburuetako zonak/Zonas de capitales,Vitoria-Gasteiz zona 06,"1.830,88",n.d.,n.d.,2020-03-30,Num_compraventas
45,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 01,"5.013,16",n.d.,n.d.,2020-03-30,Num_compraventas
46,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 02,"6.255,68","5.664,78","6.657,05",2020-03-30,Num_compraventas
47,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 03,"3.965,75","3.505,65","4.632,43",2020-03-30,Num_compraventas
48,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 04,"5.523,12",n.d.,n.d.,2020-03-30,Num_compraventas
49,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 05,"4.835,41",n.d.,n.d.,2020-03-30,Num_compraventas
50,Hiriburuetako zonak/Zonas de capitales,Donostia-San Sebastián zona 06,"3.523,94",n.d.,n.d.,2020-03-30,Num_compraventas
51,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 01,"2.710,57",n.d.,n.d.,2020-03-30,Num_compraventas
52,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 02,"2.421,17",n.d.,n.d.,2020-03-30,Num_compraventas
53,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 03,"1.992,63",n.d.,n.d.,2020-03-30,Num_compraventas
54,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 04,"2.542,25",n.d.,n.d.,2020-03-30,Num_compraventas
55,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,"2.183,99",n.d.,n.d.,2020-03-30,Num_compraventas
56,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,"3.780,81","4.305,57","3.733,46",2020-03-30,Num_compraventas
57,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,"2.449,40",n.d.,n.d.,2020-03-30,Num_compraventas
58,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,"2.240,58",n.d.,n.d.,2020-03-30,Num_compraventas
59,NaN,NaN,NaN,NaN,NaN,2020-03-30,Num_compraventas

In [ ]:
frames = [df_compraventa_2020_4, df_compraventa_2020_3, df_compraventa_2020_2, df_compraventa_2020_1]  
df_compraventa_2020 = pd.concat(frames, ignore_index=True)
df_compraventa_2020.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,EREMUA ÁMBITO,BERRIA NUEVA,Tipo
0,Nazionala/Nacional,ESPAÑA,113.799,22.842,90.957,2020-12-30,NaN,NaN,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,4.361,703,3.658,2020-12-30,NaN,NaN,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,22.770,4.831,17.939,2020-12-30,NaN,NaN,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.353,779,2.574,2020-12-30,NaN,NaN,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.276,571,1.705,2020-12-30,NaN,NaN,Num_compraventas
...,...,...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,NaN,"2.183,99",NaN,n.d.,2020-03-30,Bilbao zona 05,n.d.,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,NaN,"3.780,81",NaN,"3.733,46",2020-03-30,Bilbao zona 06,"4.305,57",Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,NaN,"2.449,40",NaN,n.d.,2020-03-30,Bilbao zona 07,n.d.,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,NaN,"2.240,58",NaN,n.d.,2020-03-30,Bilbao zona 08,n.d.,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2020-03-30,NaN,NaN,Num_compraventas

In [ ]:
# En este datasat combinado, vuelve a ser necesario modificar columnas 'EREMUA ÁMBITO', 'BERRIA NUEVA'
df_compraventa_2020.loc[: ,['Desglose', 'Territorio', 'Viv. GENERAL', 'Viv. NUEVA', 'Viv. USADA', 'Fecha', 'Tipo']]

KeyError: "['Territorio', 'Viv. NUEVA', 'Tipo'] not in index"

In [ ]:
import pandas as pd
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral19/opendata/2019.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2019-12-30')
df_compraventa_2019_4 = df.iloc[:60] #primeras x filas
df_compraventa_2019_4.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral19/opendata/2019.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2019-09-30')
df_compraventa_2019_3 = df.iloc[:60] #primeras x filas
df_compraventa_2019_3.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral19/opendata/2019.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2019-06-30')
df_compraventa_2019_2 = df.iloc[:60] #primeras x filas
df_compraventa_2019_2.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral19/opendata/2019.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2019-03-30')
df_compraventa_2019_1 = df.iloc[:60] #primeras x filas
df_compraventa_2019_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2019_4, df_compraventa_2019_3, df_compraventa_2019_2, df_compraventa_2019_1]  
df_compraventa_2019 = pd.concat(frames, ignore_index=True)
df_compraventa_2019.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,117.387,21.902,95.485,2019-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,4.608,927,3.681,2019-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,24.030,4.632,19.398,2019-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.366,804,2.562,2019-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,1.894,443,1.451,2019-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,231,81,150,2019-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,161,27,134,2019-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,207,17,190,2019-03-30,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,59,16,43,2019-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2019-03-30,Num_compraventas

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral18/opendata/2018.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2018-12-30')
df_compraventa_2018_4 = df.iloc[:60] #primeras x filas
df_compraventa_2018_4.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral18/opendata/2018.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2019-09-30')
df_compraventa_2018_3 = df.iloc[:60] # primeras x filas
df_compraventa_2018_3.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral18/opendata/2018.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2018-06-30')
df_compraventa_2018_2 = df.iloc[:60] # primeras x filas
df_compraventa_2018_2.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral18/opendata/2018.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2018-03-30')
df_compraventa_2018_1 = df.iloc[:60] #primeras x filas
df_compraventa_2018_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2018_4, df_compraventa_2018_3, df_compraventa_2018_2, df_compraventa_2018_1]  
df_compraventa_2018 = pd.concat(frames, ignore_index=True)
df_compraventa_2018.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,120.199,21.760,98.439,2018-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,4.398,832,3.566,2018-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,23.850,4.337,19.513,2018-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.131,551,2.580,2018-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.065,425,1.640,2018-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,156,6,150,2018-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,129,25,104,2018-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,119,3,116,2018-03-30,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,45,9,36,2018-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2018-03-30,Num_compraventas

In [ ]:
df_compraventa_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Desglose      236 non-null    object
 1   Territorio    236 non-null    object
 2   Viv. GENERAL  236 non-null    object
 3   Viv. NUEVA    236 non-null    object
 4   Viv. USADA    236 non-null    object
 5   Fecha         240 non-null    object
dtypes: object(6)
memory usage: 11.4+ KB

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral17/opendata/2017.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2017-12-30')
df_compraventa_2017_4 = df.iloc[:60] #primeras x filas
df_compraventa_2017_4.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral17/opendata/2017.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2017-09-30')
df_compraventa_2017_3 = df.iloc[:60] #primeras x filas
df_compraventa_2017_3.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral17/opendata/2017.2.csv',sep=';',encoding='latin-1',skiprows=2)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2017-06-30')
df_compraventa_2017_2 = df.iloc[:59] #primeras x filas
df_compraventa_2017_2.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral17/opendata/2017.1.csv',sep=';',encoding='latin-1',skiprows=2)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2017-03-30')
df_compraventa_2017_1 = df.iloc[:59] #primeras x filas
df_compraventa_2017_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2017_4, df_compraventa_2017_3, df_compraventa_2017_2, df_compraventa_2017_1]  
df_compraventa_2017 = pd.concat(frames, ignore_index=True)
df_compraventa_2017.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,111.921,19.325,92.596,2017-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,3.893,686,3.207,2017-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,22.045,3.926,18.119,2017-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3.148,598,2.550,2017-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,2.004,417,1.587,2017-12-30,Num_compraventas
...,...,...,...,...,...,...,...
233,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 04,83,n.d.,n.d.,2017-03-30,Num_compraventas
234,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,150,1,149,2017-03-30,Num_compraventas
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,175,17,158,2017-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,156,4,152,2017-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,43,9,34,2017-03-30,Num_compraventas

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral16/opendata/2016.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2016-12-30')
df_compraventa_2016_4 = df.iloc[:60] #primeras x filas
df_compraventa_2016_4.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral16/opendata/2016.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2016-09-30')
df_compraventa_2016_3 = df.iloc[:60] #primeras x filas
df_compraventa_2016_3.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral16/opendata/2016.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2016-06-30')
df_compraventa_2016_2 = df.iloc[:60] #primeras x filas
df_compraventa_2016_2.assign(Tipo='Num_compraventas')

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral16/opendata/2016.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2016-03-30')
df_compraventa_2016_1 = df.iloc[:60] #primeras x filas
df_compraventa_2016_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2016_4, df_compraventa_2016_3, df_compraventa_2016_2, df_compraventa_2016_1]  
df_compraventa_2016 = pd.concat(frames, ignore_index=True)
df_compraventa_2016.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,93.423,16.072,77.351,2016-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,3.450,736,2.714,2016-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,18.149,3.135,15.014,2016-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,2.514,484,2.030,2016-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,1.613,381,1.232,2016-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,219,4,215,2016-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,159,38,121,2016-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,108,11,97,2016-03-30,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,34,6,28,2016-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2016-03-30,Num_compraventas

In [ ]:
df_compraventa_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Desglose      236 non-null    object
 1   Territorio    236 non-null    object
 2   Viv. GENERAL  236 non-null    object
 3   Viv. NUEVA    236 non-null    object
 4   Viv. USADA    236 non-null    object
 5   Fecha         240 non-null    object
dtypes: object(6)
memory usage: 11.4+ KB

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral15/es_def/adjuntos/2015.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2015-12-30')
df_compraventa_2015_4 = df.iloc[:60] #primeras x filas
df_compraventa_2015_4.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral15/es_def/adjuntos/2015.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2015-09-30')
df_compraventa_2015_3 = df.iloc[:60] #primeras x filas
df_compraventa_2015_3.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral15/es_def/adjuntos/2015.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2015-06-30')
df_compraventa_2015_2 = df.iloc[:60] #primeras x filas
df_compraventa_2015_2.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral15/es_def/adjuntos/2015.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2015-03-30')
df_compraventa_2015_1 = df.iloc[:60] #primeras x filas
df_compraventa_2015_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2015_4, df_compraventa_2015_3, df_compraventa_2015_2, df_compraventa_2015_1]  
df_compraventa_2015 = pd.concat(frames, ignore_index=True)
df_compraventa_2015.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,84.031,15.819,68.212,2015-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,3.366,646,2.720,2015-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,16.535,3.157,13.378,2015-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,2.194,326,1.868,2015-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,1.439,412,1.027,2015-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,110,5,105,2015-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,87,7,80,2015-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,136,18,118,2015-03-30,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,30,6,24,2015-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2015-03-30,Num_compraventas

In [ ]:
df_compraventa_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Desglose      236 non-null    object
 1   Territorio    236 non-null    object
 2   Viv. GENERAL  236 non-null    object
 3   Viv. NUEVA    236 non-null    object
 4   Viv. USADA    236 non-null    object
 5   Fecha         240 non-null    object
dtypes: object(6)
memory usage: 11.4+ KB

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral14/es_def/adjuntos/2014.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2014-12-30')
df_compraventa_2014_4 = df.iloc[:60] #primeras x filas
df_compraventa_2014_4.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral14/es_def/adjuntos/2014.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2014-09-30')
df_compraventa_2014_3 = df.iloc[:60] #primeras x filas
df_compraventa_2014_3.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral14/es_def/adjuntos/2014.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2014-06-30')
df_compraventa_2014_2 = df.iloc[:60] #primeras x filas
df_compraventa_2014_2.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral14/es_def/adjuntos/2014.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2014-03-30')
df_compraventa_2014_1 = df.iloc[:60] #primeras x filas
df_compraventa_2014_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2014_4, df_compraventa_2014_3, df_compraventa_2014_2, df_compraventa_2014_1]  
df_compraventa_2014 = pd.concat(frames, ignore_index=True)
df_compraventa_2014.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,77.881,23.093,54.788,2014-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,2.805,783,2.022,2014-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,15.800,5.126,10.674,2014-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,2.115,409,1.706,2014-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,1.275,432,843,2014-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,84,8,76,2014-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,119,36,83,2014-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,96,9,87,2014-03-30,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,26,9,17,2014-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2014-03-30,Num_compraventas

In [ ]:
df_compraventa_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Desglose      236 non-null    object
 1   Territorio    236 non-null    object
 2   Viv. GENERAL  236 non-null    object
 3   Viv. NUEVA    236 non-null    object
 4   Viv. USADA    236 non-null    object
 5   Fecha         240 non-null    object
dtypes: object(6)
memory usage: 11.4+ KB

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral13/es_def/adjuntos/2013.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2013-12-30')
df_compraventa_2013_4 = df.iloc[:60] #primeras x filas
df_compraventa_2013_4.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral13/es_def/adjuntos/2013.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2013-09-30')
df_compraventa_2013_3 = df.iloc[:60] #primeras x filas
df_compraventa_2013_3.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral13/es_def/adjuntos/2013.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2013-06-30')
df_compraventa_2013_2 = df.iloc[:60] #primeras x filas
df_compraventa_2013_2.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral13/es_def/adjuntos/2013.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2013-03-30')
df_compraventa_2013_1 = df.iloc[:60] #primeras x filas
df_compraventa_2013_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2013_4, df_compraventa_2013_3, df_compraventa_2013_2, df_compraventa_2013_1]  
df_compraventa_2013 = pd.concat(frames, ignore_index=True)
df_compraventa_2013.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,72.560,33.087,39.473,2013-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,2.157,698,1.459,2013-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,14.592,7.071,7.521,2013-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,1.863,600,1.263,2013-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,1.248,608,640,2013-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 05,83,13,70,2013-03-30,Num_compraventas
236,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 06,91,38,53,2013-03-30,Num_compraventas
237,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 07,84,10,74,2013-03-30,Num_compraventas
238,Hiriburuetako zonak/Zonas de capitales,Bilbao zona 08,19,3,16,2013-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2013-03-30,Num_compraventas

In [ ]:
df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral12/es_def/adjuntos/2012.4.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2012-12-30')
df_compraventa_2012_4 = df.iloc[:60] #primeras x filas
df_compraventa_2012_4.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral12/es_def/adjuntos/2012.3.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2012-09-30')
df_compraventa_2012_3 = df.iloc[:60] #primeras x filas
df_compraventa_2012_3.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral12/es_def/adjuntos/2012.2.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2012-06-30')
df_compraventa_2012_2 = df.iloc[:60] #primeras x filas
df_compraventa_2012_2.assign(Tipo='Num_compraventas')

df = pd.read_csv('https://www.euskadi.eus/contenidos/estadistica/ovv_registral12/es_def/adjuntos/2012.1.csv',sep=';',encoding='latin-1',skiprows=3)
df= df.iloc[:, 0:5] # Primeras x columnas
df = df.rename(columns={'BANATZEA                                        DESGLOSE':'Desglose','EREMUA                                                    ÁMBITO':'Territorio'})
df = df.rename(columns={'OROKORRA GENERAL': "Viv. GENERAL",'BERRIA NUEVA': 'Viv. NUEVA','ERABILIA USADA':'Viv. USADA'})
df = df.assign(Fecha='2012-03-30')
df_compraventa_2012_1 = df.iloc[:60] #primeras x filas
df_compraventa_2012_1.assign(Tipo='Num_compraventas')

In [ ]:
frames = [df_compraventa_2012_4, df_compraventa_2012_3, df_compraventa_2012_2, df_compraventa_2012_1]  
df_compraventa_2012 = pd.concat(frames, ignore_index=True)
df_compraventa_2012.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,Tipo
0,Nazionala/Nacional,ESPAÑA,78.281,38.572,39.709,2012-12-30,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,2.549,1.085,1.464,2012-12-30,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,15.501,8.549,6.952,2012-12-30,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,2.210,893,1.317,2012-12-30,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,1.569,835,734,2012-12-30,Num_compraventas
...,...,...,...,...,...,...,...
235,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 05,81,6,75,2012-03-30,Num_compraventas
236,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 06,103,52,51,2012-03-30,Num_compraventas
237,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 07,82,6,76,2012-03-30,Num_compraventas
238,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 08,30,10,20,2012-03-30,Num_compraventas
239,NaN,NaN,NaN,NaN,NaN,2012-03-30,Num_compraventas

In [ ]:
df_compraventa_2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Desglose      236 non-null    object
 1   Territorio    236 non-null    object
 2   Viv. GENERAL  236 non-null    object
 3   Viv. NUEVA    236 non-null    object
 4   Viv. USADA    236 non-null    object
 5   Fecha         240 non-null    object
dtypes: object(6)
memory usage: 11.4+ KB

In [ ]:
frames = [df_compraventa_2023, df_compraventa_2022, df_compraventa_2021, df_compraventa_2020, df_compraventa_2019, df_compraventa_2018, df_compraventa_2017, df_compraventa_2016, df_compraventa_2015, df_compraventa_2014, df_compraventa_2013, df_compraventa_2012]  
df_compraventa = pd.concat(frames, ignore_index=True)
df_compraventa.assign(Tipo='Num_compraventas')

,Desglose,Territorio,Viv. GENERAL,Viv. NUEVA,Viv. USADA,Fecha,OROKORRA GENERAL,BERRIA NUEVA,ERABILIA USADA,EREMUA ÁMBITO,BERRIA NUEVA,Tipo
0,Nazionala/Nacional,ESPAÑA,151983,28739,123244,2023-06-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
1,Euskadi/País Vasco,EUSKADI/PAIS VASCO,5038,663,4375,2023-06-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
2,Erakunde Autonomoa/CCAA,ANDALUZIA/ANDALUCIA,30698,6269,24429,2023-06-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
3,Erakunde Autonomoa/CCAA,ARAGOI/ARAGON,3966,819,3147,2023-06-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
4,Erakunde Autonomoa/CCAA,ASTURIAS/ASTURIAS,3145,656,2489,2023-06-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
...,...,...,...,...,...,...,...,...,...,...,...,...
3174,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 05,81,6,75,2012-03-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
3175,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 06,103,52,51,2012-03-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
3176,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 07,82,6,76,2012-03-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
3177,Hiriburuetako zonak /Zonas de capitales,Bilbao zona 08,30,10,20,2012-03-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas
3178,NaN,NaN,NaN,NaN,NaN,2012-03-30,NaN,NaN,NaN,NaN,NaN,Num_compraventas

In [ ]:
df_compraventa.drop(columns=['OROKORRA GENERAL'], inplace=True)

KeyError: "['OROKORRA GENERAL'] not found in axis"